<a href="https://colab.research.google.com/github/devWorldDivey/AIML-Projects-ByDivey/blob/main/Copy_of_Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [6]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [7]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [9]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [10]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [11]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 80131.6953
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 313.6616
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 305.3244
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 294.4549
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 282.2591
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 268.6142
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 252.9684
Epoch 8/100
240/240 [==============================] - 0s 972us/step - loss: 236.2188
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 218.7270
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 200.4577
Epoch 11/100
240/240 [==============================] - 0s 2ms/step - loss: 181.1736
Epoch 12/100
240/240 [==============================] - 0s 2ms/step - 

### Predicting the results of the Test set

In [13]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 [==============================] - 0s 791us/step
[[432.77 431.23]
 [463.92 460.01]
 [467.49 461.14]
 ...
 [474.64 473.26]
 [441.41 438.  ]
 [460.63 463.28]]
